version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: bank-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank-net
  app:
    build: .
    container_name: bank_contain
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8080:8080"
    networks:
      - bank-net
volumes:
  postgres_data:
networks:
  bank-net: