spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/db.changelog.yml
    enabled: true
logging:
  level:
    root: info
    com.company.task1: debug
    org.springframework.web: warn